/**
 * Data layer for the Assa Abloy (GfS Türwächter) report app.
 *
 * All JSON files in this directory are generated by `scripts/extract-data.mjs`.
 * Import from here — never import JSON files directly in UI code.
 *
 * Usage:
 *   import { product, ranking, markets } from "@/data";
 *   import { getMarket, getODI, listMarkets } from "@/data";
 */

import type {
  ProductDecomposition,
  FunctionalPromiseData,
  ConstraintsData,
  HomeMarketCompetition,
  MarketDiscovery,
  RankingData,
  SourcesRegistry,
  MarketIndexEntry,
  JTBDData,
  ODIData,
  ValueNetworkData,
  KanoData,
  CompatibilityData,
  AlternativesData,
  MarketMeta,
  BOMData,
} from "@/types";

// ─── Static JSON imports ──────────────────────────────────────────────────────

import _product from "./product.json";
import _functionalPromise from "./functionalPromise.json";
import _constraints from "./constraints.json";
import _homeMarket from "./homeMarketCompetition.json";
import _marketDiscovery from "./marketDiscovery.json";
import _ranking from "./ranking.json";
import _sources from "./sources.json";
import _marketsIndex from "./markets/index.json";

// ─── Market data imports — one per slug ───────────────────────────────────────

// colleges_universities
import _collegesUniversitiesMeta from "./markets/colleges_universities/meta.json";
import _collegesUniversitiesJtbd from "./markets/colleges_universities/jtbd.json";
import _collegesUniversitiesOdi from "./markets/colleges_universities/odi.json";
import _collegesUniversitiesVn from "./markets/colleges_universities/valueNetwork.json";
import _collegesUniversitiesKano from "./markets/colleges_universities/kano.json";
import _collegesUniversitiesCompat from "./markets/colleges_universities/compatibility.json";
import _collegesUniversitiesAlt from "./markets/colleges_universities/alternatives.json";
import _collegesUniversitiesBom from "./markets/colleges_universities/bom.json";

// continuing_care_retirement
import _ccrcMeta from "./markets/continuing_care_retirement/meta.json";
import _ccrcJtbd from "./markets/continuing_care_retirement/jtbd.json";
import _ccrcOdi from "./markets/continuing_care_retirement/odi.json";
import _ccrcVn from "./markets/continuing_care_retirement/valueNetwork.json";
import _ccrcKano from "./markets/continuing_care_retirement/kano.json";
import _ccrcCompat from "./markets/continuing_care_retirement/compatibility.json";
import _ccrcAlt from "./markets/continuing_care_retirement/alternatives.json";
import _ccrcBom from "./markets/continuing_care_retirement/bom.json";

// data_centers
import _dataCentersMeta from "./markets/data_centers/meta.json";
import _dataCentersJtbd from "./markets/data_centers/jtbd.json";
import _dataCentersOdi from "./markets/data_centers/odi.json";
import _dataCentersVn from "./markets/data_centers/valueNetwork.json";
import _dataCentersKano from "./markets/data_centers/kano.json";
import _dataCentersCompat from "./markets/data_centers/compatibility.json";
import _dataCentersAlt from "./markets/data_centers/alternatives.json";
import _dataCentersBom from "./markets/data_centers/bom.json";

// elementary_secondary_schools
import _k12Meta from "./markets/elementary_secondary_schools/meta.json";
import _k12Jtbd from "./markets/elementary_secondary_schools/jtbd.json";
import _k12Odi from "./markets/elementary_secondary_schools/odi.json";
import _k12Vn from "./markets/elementary_secondary_schools/valueNetwork.json";
import _k12Kano from "./markets/elementary_secondary_schools/kano.json";
import _k12Compat from "./markets/elementary_secondary_schools/compatibility.json";
import _k12Alt from "./markets/elementary_secondary_schools/alternatives.json";
import _k12Bom from "./markets/elementary_secondary_schools/bom.json";

// facilities_support_services
import _facilitiesMeta from "./markets/facilities_support_services/meta.json";
import _facilitiesJtbd from "./markets/facilities_support_services/jtbd.json";
import _facilitiesOdi from "./markets/facilities_support_services/odi.json";
import _facilitiesVn from "./markets/facilities_support_services/valueNetwork.json";
import _facilitiesKano from "./markets/facilities_support_services/kano.json";
import _facilitiesCompat from "./markets/facilities_support_services/compatibility.json";
import _facilitiesAlt from "./markets/facilities_support_services/alternatives.json";
import _facilitiesBom from "./markets/facilities_support_services/bom.json";

// general_medical_surgical_hospitals
import _hospitalsMeta from "./markets/general_medical_surgical_hospitals/meta.json";
import _hospitalsJtbd from "./markets/general_medical_surgical_hospitals/jtbd.json";
import _hospitalsOdi from "./markets/general_medical_surgical_hospitals/odi.json";
import _hospitalsVn from "./markets/general_medical_surgical_hospitals/valueNetwork.json";
import _hospitalsKano from "./markets/general_medical_surgical_hospitals/kano.json";
import _hospitalsCompat from "./markets/general_medical_surgical_hospitals/compatibility.json";
import _hospitalsAlt from "./markets/general_medical_surgical_hospitals/alternatives.json";
import _hospitalsBom from "./markets/general_medical_surgical_hospitals/bom.json";

// general_warehousing_storage
import _warehousingMeta from "./markets/general_warehousing_storage/meta.json";
import _warehousingJtbd from "./markets/general_warehousing_storage/jtbd.json";
import _warehousingOdi from "./markets/general_warehousing_storage/odi.json";
import _warehousingVn from "./markets/general_warehousing_storage/valueNetwork.json";
import _warehousingKano from "./markets/general_warehousing_storage/kano.json";
import _warehousingCompat from "./markets/general_warehousing_storage/compatibility.json";
import _warehousingAlt from "./markets/general_warehousing_storage/alternatives.json";
import _warehousingBom from "./markets/general_warehousing_storage/bom.json";

// hotels_motels
import _hotelsMeta from "./markets/hotels_motels/meta.json";
import _hotelsJtbd from "./markets/hotels_motels/jtbd.json";
import _hotelsOdi from "./markets/hotels_motels/odi.json";
import _hotelsVn from "./markets/hotels_motels/valueNetwork.json";
import _hotelsKano from "./markets/hotels_motels/kano.json";
import _hotelsCompat from "./markets/hotels_motels/compatibility.json";
import _hotelsAlt from "./markets/hotels_motels/alternatives.json";
import _hotelsBom from "./markets/hotels_motels/bom.json";

// lessors_nonresidential_buildings
import _lessorsMeta from "./markets/lessors_nonresidential_buildings/meta.json";
import _lessorsJtbd from "./markets/lessors_nonresidential_buildings/jtbd.json";
import _lessorsOdi from "./markets/lessors_nonresidential_buildings/odi.json";
import _lessorsVn from "./markets/lessors_nonresidential_buildings/valueNetwork.json";
import _lessorsKano from "./markets/lessors_nonresidential_buildings/kano.json";
import _lessorsCompat from "./markets/lessors_nonresidential_buildings/compatibility.json";
import _lessorsAlt from "./markets/lessors_nonresidential_buildings/alternatives.json";
import _lessorsBom from "./markets/lessors_nonresidential_buildings/bom.json";

// museums_historical_sites
import _museumsMeta from "./markets/museums_historical_sites/meta.json";
import _museumsJtbd from "./markets/museums_historical_sites/jtbd.json";
import _museumsOdi from "./markets/museums_historical_sites/odi.json";
import _museumsVn from "./markets/museums_historical_sites/valueNetwork.json";
import _museumsKano from "./markets/museums_historical_sites/kano.json";
import _museumsCompat from "./markets/museums_historical_sites/compatibility.json";
import _museumsAlt from "./markets/museums_historical_sites/alternatives.json";
import _museumsBom from "./markets/museums_historical_sites/bom.json";

// ─── Typed exports ────────────────────────────────────────────────────────────

export const product = _product as unknown as ProductDecomposition;
export const functionalPromise = _functionalPromise as unknown as FunctionalPromiseData;
export const constraints = _constraints as unknown as ConstraintsData;
export const homeMarket = _homeMarket as unknown as HomeMarketCompetition;
export const marketDiscovery = _marketDiscovery as unknown as MarketDiscovery;
export const ranking = _ranking as unknown as RankingData;
export const sources = _sources as unknown as SourcesRegistry;
export const marketsIndex = _marketsIndex as unknown as MarketIndexEntry[];

// ─── Kano normalizer (JSON uses name/kanoClass/overallFit; type uses featureName/kanoClassification/scores.overall) ─
function normalizeKano(raw: any): KanoData {
  if (!raw?.features) return raw as KanoData;
  return {
    ...raw,
    features: raw.features.map((f: any) => ({
      featureName: f.featureName ?? f.name ?? "",
      kanoClassification: f.kanoClassification ?? f.kanoClass ?? "indifferent",
      scores: {
        ...(f.scores ?? {}),
        overall: f.scores?.overall ?? f.overallFit ?? 0,
      },
      rationale: f.rationale ?? "",
    })),
  } as KanoData;
}

// ─── Per-market data bundles ──────────────────────────────────────────────────

export interface MarketBundle {
  meta: MarketMeta;
  jtbd: JTBDData;
  odi: ODIData;
  valueNetwork: ValueNetworkData;
  kano: KanoData;
  compatibility: CompatibilityData;
  alternatives: AlternativesData;
  bom: BOMData;
}

const _marketBundles: Record<string, MarketBundle> = {
  "colleges_universities": {
    meta: _collegesUniversitiesMeta as unknown as MarketMeta,
    jtbd: _collegesUniversitiesJtbd as unknown as JTBDData,
    odi: _collegesUniversitiesOdi as unknown as ODIData,
    valueNetwork: _collegesUniversitiesVn as unknown as ValueNetworkData,
    kano: normalizeKano(_collegesUniversitiesKano),
    compatibility: _collegesUniversitiesCompat as unknown as CompatibilityData,
    alternatives: _collegesUniversitiesAlt as unknown as AlternativesData,
    bom: _collegesUniversitiesBom as unknown as BOMData,
  },
  "continuing_care_retirement": {
    meta: _ccrcMeta as unknown as MarketMeta,
    jtbd: _ccrcJtbd as unknown as JTBDData,
    odi: _ccrcOdi as unknown as ODIData,
    valueNetwork: _ccrcVn as unknown as ValueNetworkData,
    kano: normalizeKano(_ccrcKano),
    compatibility: _ccrcCompat as unknown as CompatibilityData,
    alternatives: _ccrcAlt as unknown as AlternativesData,
    bom: _ccrcBom as unknown as BOMData,
  },
  "data_centers": {
    meta: _dataCentersMeta as unknown as MarketMeta,
    jtbd: _dataCentersJtbd as unknown as JTBDData,
    odi: _dataCentersOdi as unknown as ODIData,
    valueNetwork: _dataCentersVn as unknown as ValueNetworkData,
    kano: normalizeKano(_dataCentersKano),
    compatibility: _dataCentersCompat as unknown as CompatibilityData,
    alternatives: _dataCentersAlt as unknown as AlternativesData,
    bom: _dataCentersBom as unknown as BOMData,
  },
  "elementary_secondary_schools": {
    meta: _k12Meta as unknown as MarketMeta,
    jtbd: _k12Jtbd as unknown as JTBDData,
    odi: _k12Odi as unknown as ODIData,
    valueNetwork: _k12Vn as unknown as ValueNetworkData,
    kano: normalizeKano(_k12Kano),
    compatibility: _k12Compat as unknown as CompatibilityData,
    alternatives: _k12Alt as unknown as AlternativesData,
    bom: _k12Bom as unknown as BOMData,
  },
  "facilities_support_services": {
    meta: _facilitiesMeta as unknown as MarketMeta,
    jtbd: _facilitiesJtbd as unknown as JTBDData,
    odi: _facilitiesOdi as unknown as ODIData,
    valueNetwork: _facilitiesVn as unknown as ValueNetworkData,
    kano: normalizeKano(_facilitiesKano),
    compatibility: _facilitiesCompat as unknown as CompatibilityData,
    alternatives: _facilitiesAlt as unknown as AlternativesData,
    bom: _facilitiesBom as unknown as BOMData,
  },
  "general_medical_surgical_hospitals": {
    meta: _hospitalsMeta as unknown as MarketMeta,
    jtbd: _hospitalsJtbd as unknown as JTBDData,
    odi: _hospitalsOdi as unknown as ODIData,
    valueNetwork: _hospitalsVn as unknown as ValueNetworkData,
    kano: normalizeKano(_hospitalsKano),
    compatibility: _hospitalsCompat as unknown as CompatibilityData,
    alternatives: _hospitalsAlt as unknown as AlternativesData,
    bom: _hospitalsBom as unknown as BOMData,
  },
  "general_warehousing_storage": {
    meta: _warehousingMeta as unknown as MarketMeta,
    jtbd: _warehousingJtbd as unknown as JTBDData,
    odi: _warehousingOdi as unknown as ODIData,
    valueNetwork: _warehousingVn as unknown as ValueNetworkData,
    kano: normalizeKano(_warehousingKano),
    compatibility: _warehousingCompat as unknown as CompatibilityData,
    alternatives: _warehousingAlt as unknown as AlternativesData,
    bom: _warehousingBom as unknown as BOMData,
  },
  "hotels_motels": {
    meta: _hotelsMeta as unknown as MarketMeta,
    jtbd: _hotelsJtbd as unknown as JTBDData,
    odi: _hotelsOdi as unknown as ODIData,
    valueNetwork: _hotelsVn as unknown as ValueNetworkData,
    kano: normalizeKano(_hotelsKano),
    compatibility: _hotelsCompat as unknown as CompatibilityData,
    alternatives: _hotelsAlt as unknown as AlternativesData,
    bom: _hotelsBom as unknown as BOMData,
  },
  "lessors_nonresidential_buildings": {
    meta: _lessorsMeta as unknown as MarketMeta,
    jtbd: _lessorsJtbd as unknown as JTBDData,
    odi: _lessorsOdi as unknown as ODIData,
    valueNetwork: _lessorsVn as unknown as ValueNetworkData,
    kano: normalizeKano(_lessorsKano),
    compatibility: _lessorsCompat as unknown as CompatibilityData,
    alternatives: _lessorsAlt as unknown as AlternativesData,
    bom: _lessorsBom as unknown as BOMData,
  },
  "museums_historical_sites": {
    meta: _museumsMeta as unknown as MarketMeta,
    jtbd: _museumsJtbd as unknown as JTBDData,
    odi: _museumsOdi as unknown as ODIData,
    valueNetwork: _museumsVn as unknown as ValueNetworkData,
    kano: normalizeKano(_museumsKano),
    compatibility: _museumsCompat as unknown as CompatibilityData,
    alternatives: _museumsAlt as unknown as AlternativesData,
    bom: _museumsBom as unknown as BOMData,
  },
};

// Convenience alias: all bundles as a record
export const markets = _marketBundles;

// ─── Helper functions ─────────────────────────────────────────────────────────

/**
 * Return the full data bundle for a market slug.
 * Throws if the slug is not registered.
 */
export function getMarket(slug: string): MarketBundle {
  const bundle = _marketBundles[slug];
  if (!bundle) {
    throw new Error(
      `Unknown market slug: "${slug}". Available: ${Object.keys(_marketBundles).join(", ")}`
    );
  }
  return bundle;
}

/**
 * Return the ODI data for a market slug.
 */
export function getODI(slug: string): ODIData {
  return getMarket(slug).odi;
}

/**
 * Return the JTBD data for a market slug.
 */
export function getJTBD(slug: string): JTBDData {
  return getMarket(slug).jtbd;
}

/**
 * Return the Kano feature-fit data for a market slug.
 */
export function getKano(slug: string): KanoData {
  return getMarket(slug).kano;
}

/**
 * Return the value network data for a market slug.
 */
export function getValueNetwork(slug: string): ValueNetworkData {
  return getMarket(slug).valueNetwork;
}

/**
 * Return the compatibility assessment for a market slug.
 */
export function getCompatibility(slug: string): CompatibilityData {
  return getMarket(slug).compatibility;
}

/**
 * List all market index entries (ordered as in index.json).
 */
export function listMarkets(): MarketIndexEntry[] {
  return marketsIndex;
}

/**
 * List only new-market candidates (excludes any reference entries).
 */
export function listNewMarkets(): MarketIndexEntry[] {
  return marketsIndex.filter((m) => !m.isReference);
}

/**
 * Return the meta record for a market slug.
 */
export function getMarketMeta(slug: string): MarketMeta {
  return getMarket(slug).meta;
}

/**
 * Return all ranked markets sorted by composite score descending.
 */
export function getRankedMarkets() {
  return [...ranking.rankedMarkets].sort(
    (a, b) => b.scores.composite - a.scores.composite
  );
}

/**
 * Look up a source by its prefixed ID (e.g. "PROD-S01").
 */
export function getSource(prefixedId: string): import("@/types").Source | undefined {
  return (sources as SourcesRegistry)[prefixedId];
}

/**
 * Return the Bill of Materials data for a market slug.
 */
export function getBOM(slug: string): BOMData {
  return getMarket(slug).bom;
}
